### ISSUE TITLE
Displaying mobile app pop-up on mobile view

### ISSUE THREAD

**Issue by ayo-klaytn** [klaytn/klaytn-safe-react#15]
## Description
Klaytn Safe pops up a notification when the web app is switched from desktop version to mobile version. Since we do not support mobile yet, this sentence should be removed. 

"Klaytn safe web app is not optimized for mobile" is a perfect fit!

## Screenshots
![WhatsApp Image 2022-12-06 at 12 53 23 PM](https://user-images.githubusercontent.com/116874395/205907116-aed63acd-8754-47c2-8fa6-4b58005a8b8e.jpeg)

**Comment by praveen-kaia** [comment]
Fixed as part of #17

**Comment by praveen-kaia** [comment]
merged into main branch and issue is resolved.
